name: Flat

on:
  push:
    paths:
      - .github/workflows/flat.yml # Only run a new workflow every time this file (flat.yaml) file changes
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: '0 0 1 * *' # Run once a month

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps: # This workflow has 2 steps
    
      # The first step is to check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v2
      
      # The third step is a Flat Action step. We fetch the data in the http_url and save it as downloaded_filename
      - name: Fetch data 
        uses: githubocto/flat@v3
        with:
          http_url: https://api.coindesk.com/v2/bpi/currentprice.json # The data to fetch once a month
          downloaded_filename: btc-price.json # The http_url gets saved and renamed in our repository as btc-price.json
