name: Create Unity Package

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        find Assets/ -name \*.meta >> metaList

    - run: mkdir unitypackage

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'unitypackage/URPVertexDensity.unitypackage'
        include-files: metaList
    - uses: actions/upload-artifact@master
      with:
        path: unitypackage
        name: package
